########################
# Spring boot properties
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
########################
spring:
  profiles:
    active:
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    #    url: jdbc:postgresql://localhost:26257/retry_demo?sslmode=disable
    url: jdbc:postgresql://192.168.1.99:26257/retry_demo?sslmode=disable
    driver-class-name: org.postgresql.Driver
    username: root
    password:
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 15000
      validation-timeout: 5000
      maximum-pool-size: 5
      minimum-idle: 5
      register-mbeans: false

  flyway:
    enabled: true
    clean-on-validation-error: true
    baseline-on-migrate: true
    locations: classpath:db/

  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.CockroachDialect
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 8090
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always

logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr([%logger{39}]){cyan} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"